name: Build
on:
  push:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build .
    #TODO push to image registry